branches:
  only:
    - master
    - appveyor

environment:
  matrix:
    - MSYSTEM: MINGW64
    - MSYSTEM: MINGW32

shallow_clone: true
test: off

install:
  # Update core packages
  - C:\msys64\usr\bin\pacman -Syyuu --noconfirm
  # Update non-core packages
  - C:\msys64\usr\bin\pacman -Suu --noconfirm
  # Install required MSYS2 packages
  - C:\msys64\usr\bin\pacman -S --noconfirm --needed perl python pkg-config
  # Now MSYS2 is up to date, do the rest of the install from a bash script
  - C:\msys64\usr\bin\bash -lc "cd \"$APPVEYOR_BUILD_FOLDER\" && exec ./TOOLS/appveyor-install.sh"
build_script:
  - C:\msys64\usr\bin\bash -lc "cd \"$APPVEYOR_BUILD_FOLDER\" && exec ./TOOLS/appveyor-build.sh"
on_failure:
  - type "%APPVEYOR_BUILD_FOLDER%\build\config.log"

cache:
  - C:\msys64\var\cache\pacman\pkg

after_build:
  - mkdir c:\snapshots
  - 7z a c:\snapshots\mpv_%MSYSTEM%_snapshot.zip . -x!.git
  - copy /y c:\snapshots\mpv_%MSYSTEM%_snapshot.zip .
  
artifacts:
  - path: mpv_$(MSYSTEM)_snapshot.zip
    name: mpv windows $(MSYSTEM) snapshot zip
